# Generated by Django 5.0.3 on 2024-04-24 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('rest_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=21)),
                ('p_code', models.CharField(max_length=10)),
                ('colony', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('num_ext', models.SmallIntegerField()),
                ('num_int', models.SmallIntegerField(blank=True, null=True)),
                ('max_cap', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('resrv_id', models.AutoField(primary_key=True, serialize=False)),
                ('hr', models.TimeField()),
                ('date', models.DateField()),
                ('num_people', models.PositiveSmallIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinespotapp.client')),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinespotapp.restaurant')),
            ],
        ),
    ]
