# Generated by Django 5.0.3 on 2024-05-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinespotapp', '0002_rename_type_restaurant_description_client_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='num_ext',
            field=models.SmallIntegerField(default=0),
        ),
    ]
