# Generated by Django 5.0.3 on 2024-05-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinespotapp', '0003_alter_restaurant_num_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='', max_length=21),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='colony',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='country',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='max_cap',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='p_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='state',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='street',
            field=models.CharField(default='', max_length=100),
        ),
    ]
