# Generated by Django 5.0.3 on 2024-05-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinespotapp', '0004_alter_restaurant_city_alter_restaurant_colony_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='f_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='l_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(default='', max_length=20),
        ),
    ]
